// <auto-generated />
using ASSIGNMENT2PART1.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ASSIGNMENT2PART2.Migrations
{
    [DbContext(typeof(DBContext))]
    partial class DBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ASSIGNMENT2PART1.Models.Category", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Url");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Url = "general",
                            Name = "General"
                        },
                        new
                        {
                            Url = "hist",
                            Name = "History"
                        });
                });

            modelBuilder.Entity("ASSIGNMENT2PART1.Models.FAQs", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Answer")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CategoryUrl")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TopicUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryUrl");

                    b.HasIndex("TopicUrl");

                    b.ToTable("FAQs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Answer = "A CSS framework for creating responsive web apps for multiple screen sizes.",
                            CategoryUrl = "general",
                            Question = "What is Bootstrap?",
                            TopicUrl = "bootstrap"
                        },
                        new
                        {
                            Id = 2,
                            Answer = "In 2011.",
                            CategoryUrl = "hist",
                            Question = "When was Bootstrap first released?",
                            TopicUrl = "bootstrap"
                        },
                        new
                        {
                            Id = 3,
                            Answer = "Yes, Bootstrap is designed to be mobile-first, meaning that it prioritizes the mobile viewing experience and adapts to different screen sizes and devices.",
                            CategoryUrl = "general",
                            Question = "Is Bootstrap mobile-friendly?",
                            TopicUrl = "bootstrap"
                        },
                        new
                        {
                            Id = 4,
                            Answer = "Yes, Bootstrap includes a set of JavaScript plugins that enhance the functionality of its components. ",
                            CategoryUrl = "general",
                            Question = "Does Bootstrap support JavaScript functionality?",
                            TopicUrl = "bootstrap"
                        },
                        new
                        {
                            Id = 5,
                            Answer = " Bootstrap was created by Mark Otto and Jacob Thornton, both of whom were engineers at Twitter at the time.",
                            CategoryUrl = "hist",
                            Question = "Who created Bootstrap?",
                            TopicUrl = "bootstrap"
                        },
                        new
                        {
                            Id = 6,
                            Answer = "A general purpose scripting language that executes in a web browser.",
                            CategoryUrl = "general",
                            Question = "What is Javascript?",
                            TopicUrl = "js"
                        },
                        new
                        {
                            Id = 7,
                            Answer = "In 1995.",
                            CategoryUrl = "hist",
                            Question = "When was Javascript first released?",
                            TopicUrl = "js"
                        },
                        new
                        {
                            Id = 8,
                            Answer = "The creation of JavaScript was driven by the need for a lightweight scripting language that could be executed on the client-side within web browsers.",
                            CategoryUrl = "hist",
                            Question = "What was the motivation behind creating JavaScript?",
                            TopicUrl = "js"
                        },
                        new
                        {
                            Id = 9,
                            Answer = "No, JavaScript is not the same as Java. Despite the similar names, they are two distinct programming languages with different syntax, semantics, and purposes.",
                            CategoryUrl = "general",
                            Question = "Is JavaScript the same as Java?",
                            TopicUrl = "js"
                        },
                        new
                        {
                            Id = 10,
                            Answer = "A general purpose object oriented language that executes in a web browser.",
                            CategoryUrl = "general",
                            Question = "What is C#?",
                            TopicUrl = "csharp"
                        },
                        new
                        {
                            Id = 11,
                            Answer = "In 2002.",
                            CategoryUrl = "hist",
                            Question = "When was C# first released?",
                            TopicUrl = "csharp"
                        });
                });

            modelBuilder.Entity("ASSIGNMENT2PART1.Models.Topic", b =>
                {
                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Url");

                    b.ToTable("Topics");

                    b.HasData(
                        new
                        {
                            Url = "bootstrap",
                            Name = "Bootstrap"
                        },
                        new
                        {
                            Url = "csharp",
                            Name = "C#"
                        },
                        new
                        {
                            Url = "js",
                            Name = "Javascript"
                        });
                });

            modelBuilder.Entity("ASSIGNMENT2PART1.Models.FAQs", b =>
                {
                    b.HasOne("ASSIGNMENT2PART1.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryUrl");

                    b.HasOne("ASSIGNMENT2PART1.Models.Topic", "Topic")
                        .WithMany()
                        .HasForeignKey("TopicUrl")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Topic");
                });
#pragma warning restore 612, 618
        }
    }
}
